# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "dik",
  "password": "1234567",
  "email": "dik@example.com",
  "type": "usual"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "dik@example.com",
  "password": "1234567"
}

###

## Отправить изображение

POST http://localhost:5000/users/6659d6ab23b3ac559235710f/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/user/Desktop/myAvatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJlbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJiZW4iLCJpZCI6IjY2NjM0Yzc4ODBlYTVjZWViNzI3Njc0NCIsImlhdCI6MTcxNzc4MzY3NywiZXhwIjoxNzE3OTU2NDc3fQ.3J1aZjNNwsSTvH2wWGj5wA53cuA8NaxgTqSx_U9ECRQ

###

