# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Genny",
  "password": "1234567",
  "email": "genny@example.com",
  "type": "usual",
  "avatarUrl": "https://15.design.htmlacademy.pro/static/avatar/4.jpg"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "ben@example.com",
  "password": "1234567"
}

###
