# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "alina",
  "password": "1234567",
  "email": "alina@example.com",
  "type": "usual"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "alina@example.com",
  "password": "1234567"
}

###

## Отправить изображение

POST http://localhost:5000/users/6659d6ab23b3ac559235710f/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/user/Desktop/myAvatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hQGV4YW1wbGUuY29tIiwibmFtZSI6ImFsaW5hIiwiaWQiOiI2NjZjMjZmODc5MWM1OWI2MWU4MzgxZTAiLCJpYXQiOjE3MTgzNjM5MTcsImV4cCI6MTcxODUzNjcxN30.JWgbvtG2E7f11aGmAK2ApbITrwQeuUyZTh8W8O4fYgA

###

