# OFFERS
## Получить список предложений
GET http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hQGV4YW1wbGUuY29tIiwibmFtZSI6ImFsaW5hIiwiaWQiOiI2NjZjMjZmODc5MWM1OWI2MWU4MzgxZTAiLCJpYXQiOjE3MTgzNjQwMDIsImV4cCI6MTcxODUzNjgwMn0.FUkAD2StnNoxmNaYuedgPiEBnInSu8YrZqxupwcFM8A

###

## Добавить новое предложение
POST http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hQGV4YW1wbGUuY29tIiwibmFtZSI6ImFsaW5hIiwiaWQiOiI2NjZjMjZmODc5MWM1OWI2MWU4MzgxZTAiLCJpYXQiOjE3MTgzNjQwMDIsImV4cCI6MTcxODUzNjgwMn0.FUkAD2StnNoxmNaYuedgPiEBnInSu8YrZqxupwcFM8A

{
  "title": "Wood and stone place123456",
  "description": "0 The building is green and from 18th century, but where the bustle of the city comes.",
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 50.938361,
      "longitude": 6.959974
    }
  },
  "images": [
    "https://15.design.htmlacademy.pro/static/hotel/8.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/10.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/6.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/1.jpg"
  ],
  "isFavorite": true,
  "isPremium": false,
  "type": "room",
  "room": 3,
  "bedroom": 4,
  "price": 50555,
  "goods": [
    "Breakfast",
    "Laptop friendly workspace"
  ],
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

## Детальная информация по предложению.

GET  http://localhost:5000/offers/666c3a84ea32d1de6d16af4c/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hdmRvdmljaGVua28ucnVAZ21haWwuY29tIiwibmFtZSI6ImFsaW5hdmRvdmljaGVuayIsImlkIjoiNjY2YTg5Mzg2NWViYmQwOWUwMjYwZjM2IiwiaWF0IjoxNzE4MjU4MTA2LCJleHAiOjE3MTg0MzA5MDZ9.u0smTfFxo-jB6MabTaTKry-l69H0wkYkQ8bQZ9gSSaU
###

## Удалить предложение.

DELETE  http://localhost:5000/offers/666a7a6f88c4cae625709b16/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hdmRvdmljaGVua28ucnVAZ21haWwuY29tIiwibmFtZSI6ImFsaW5hdmRvdmljaGVuayIsImlkIjoiNjY2YTg5Mzg2NWViYmQwOWUwMjYwZjM2IiwiaWF0IjoxNzE4MjU4MTA2LCJleHAiOjE3MTg0MzA5MDZ9.u0smTfFxo-jB6MabTaTKry-l69H0wkYkQ8bQZ9gSSaU

###

## Редактирование предложения

PUT  http://localhost:5000/offers/666c1c1743aaf03ea981667a/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJlbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJCZW4iLCJpZCI6IjY2NTk3ZWY3ZTEyYzIzMmI3Yjc5ZjJlZCIsImlhdCI6MTcxNzY3NjAwMiwiZXhwIjoxNzE3ODQ4ODAyfQ.eSoRvVMa_g_ZHEMy5iPg3iETumoaeuQrgFB8oZrnNgQ

{
  "title": "Luxurious apartment at great location",
}

###

## Изменить состояние флага isFavorite на true
POST http://localhost:5000/offers/favorites/666c3a84ea32d1de6d16af4c/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hdmRvdmljaGVua28ucnVAZ21haWwuY29tIiwibmFtZSI6ImFsaW5hdmRvdmljaGVuayIsImlkIjoiNjY2YTg5Mzg2NWViYmQwOWUwMjYwZjM2IiwiaWF0IjoxNzE4MjU4MTA2LCJleHAiOjE3MTg0MzA5MDZ9.u0smTfFxo-jB6MabTaTKry-l69H0wkYkQ8bQZ9gSSaU


###

## Изменить состояние флага isFavorite на false
DELETE http://localhost:5000/offers/favorites/666a7a6f88c4cae625709af5/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hQGV4YW1wbGUuY29tIiwibmFtZSI6ImFsaW5hIiwiaWQiOiI2NjZjMjZmODc5MWM1OWI2MWU4MzgxZTAiLCJpYXQiOjE3MTgzNjQwMDIsImV4cCI6MTcxODUzNjgwMn0.FUkAD2StnNoxmNaYuedgPiEBnInSu8YrZqxupwcFM8A

###

## Получить список премиальных предложений по городу
GET http://localhost:5000/offers/premium/?cityName=Hamburg HTTP/1.1
Content-Type: application/json

###

## Получить список избранных предложений для пользователя
GET http://localhost:5000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hQGV4YW1wbGUuY29tIiwibmFtZSI6ImFsaW5hIiwiaWQiOiI2NjZjMjZmODc5MWM1OWI2MWU4MzgxZTAiLCJpYXQiOjE3MTgzNjQwMDIsImV4cCI6MTcxODUzNjgwMn0.FUkAD2StnNoxmNaYuedgPiEBnInSu8YrZqxupwcFM8A

###

## Получить список отзывов для оффера
GET http://localhost:5000/offers/666a7a6f88c4cae625709af5/reviews HTTP/1.1
Content-Type: application/json

###


## Загрузить изображение для объявления
POST http://localhost:5000/offers/666968a7cc822432a1dbb88b/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpa0BleGFtcGxlLmNvbSIsIm5hbWUiOiJkaWsiLCJpZCI6IjY2Njk2OWVjOTg4ODg1NDQ2NzQwN2MyZCIsImlhdCI6MTcxODE4NDQ2NSwiZXhwIjoxNzE4MzU3MjY1fQ.dUmy0U0eDQArJzzTSZnWM-H80wOeId1eRrG4Z3-0yuE
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="screen.png"
Content-Type: image/png

< /Users/spider_net/Desktop/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###

