# OFFERS
## Получить список предложений
GET http://localhost:5000/offers/?count=3 HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение
POST http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Inpob2x1ZEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IkFydGVtIFpob2x1ZCIsImlkIjoiNjVlMWRlYjQ0M2Y5OWQzZGYyZmU5OWVkIiwiaWF0IjoxNzA5MzA0MjE2LCJleHAiOjE3MDk0NzcwMTZ9.dWjkvdYZV32nGvKKZRAfeXPS-uHQOL3gn-BpGZ5N560

{
  "title": "Wood and stone place123",
  "description": "The building is green and from 18th century, but where the bustle of the city comes.",
  "publicDate": "2024-04-30T13:05:42.068Z",
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 50.938361,
      "longitude": 6.959974
    }
  },
  "previewImage": "previewImage2.jpg",
  "images": [
    "https://15.design.htmlacademy.pro/static/hotel/8.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/10.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/6.jpg",
    "https://15.design.htmlacademy.pro/static/hotel/1.jpg"
  ],
  "isFavorite": true,
  "isPremium": false,
  "type": "room",
  "room": 3,
  "bedroom": 4,
  "price": 50555,
  "goods": [
    "Breakfast",
    "Laptop friendly workspace"
  ],
  "hostId": "6656d4e79e76066c486b948b",
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

## Детальная информация по предложению.

GET  http://localhost:5000/offers/66587fe58b1bc411de595c06/ HTTP/1.1
Content-Type: application/json

###

## Удалить предложение.

DELETE  http://localhost:5000/offers/6656d4e79e76066c486b9492/ HTTP/1.1
Content-Type: application/json

###

## Редактирование предложения

PUT  http://localhost:5000/offers/66587fe58b1bc411de595c05/ HTTP/1.1
Content-Type: application/json

{
  "title": "Luxurious apartment at great location",
  "hostId": "664edefd9a6d587d62439437"
}

###

## Получить список премиальных предложений по городу
GET http://localhost:5000/offers/premium/?cityName=Hamburg HTTP/1.1
Content-Type: application/json

###
