# REVIEWS
## Создание отзыва

POST  http://localhost:5000/reviews/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJlbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJCZW4iLCJpZCI6IjY2NTk3ZWY3ZTEyYzIzMmI3Yjc5ZjJlZCIsImlhdCI6MTcxNzY0ODc5NSwiZXhwIjoxNzE3ODIxNTk1fQ.eHTh_xtOb1rY7tSgcB3cULcc-QC4M64NtjIQl1roRlc
{
  "offerId": "66587fe58b1bc411de595c05",
  "comment": "An independent House, strategically located between Rembrand Square and National Opera,",
  "publishDate": "2024-04-30T13:05:42.068Z",
  "rating": 3,
}

###
