# REVIEWS
## Создание отзыва

POST  http://localhost:5000/reviews/ HTTP/1.1
Content-Type: application/json

{
  "offerId": "6654b30510a74dfaf8eec537",
  "comment": "Новый отзыв3",
  "publishDate": "2024-04-30T13:05:42.068Z",
  "rating": 5,
  "hostId": "664ee08d0030834403a91fa4"
}

###
