# REVIEWS
## Создание отзыва

POST  http://localhost:5000/reviews/666a7a6f88c4cae625709b03/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFsaW5hdmRvdmljaGVua28ucnVAZ21haWwuY29tIiwibmFtZSI6ImFsaW5hdmRvdmljaGVuayIsImlkIjoiNjY2YTg5Mzg2NWViYmQwOWUwMjYwZjM2IiwiaWF0IjoxNzE4MjU4MTA2LCJleHAiOjE3MTg0MzA5MDZ9.u0smTfFxo-jB6MabTaTKry-l69H0wkYkQ8bQZ9gSSaU

{
  "comment": "An independent House, strategically located between Rembrand Square and National Opera,",
  "publishDate": "2024-04-30T13:05:42.068Z",
  "rating": 3
}

###
